# Generated by Django 5.1 on 2024-09-15 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traveller',
            fields=[
                ('traveller_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('mobile', models.IntegerField()),
                ('country', models.CharField(max_length=20)),
                ('pancard', models.CharField(max_length=20)),
                ('passportNo', models.CharField(max_length=20)),
                ('issueDate', models.DateField()),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.booking')),
            ],
        ),
    ]
