# Generated by Django 5.1 on 2024-09-20 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_international'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='destination',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='booking',
            name='travel_date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='traveller',
            name='country',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='traveller',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='traveller',
            name='issueDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='traveller',
            name='mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='traveller',
            name='pancard',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='traveller',
            name='passportNo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
