# Generated by Django 5.1 on 2024-10-01 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_alter_booking_booking_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='refrenceNo',
        ),
    ]
